import { getChatByToken } from '@/actions/share-actions';
import { notFound } from 'next/navigation';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { Bot, User as UserIcon, Heart, Share2 } from 'lucide-react';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Markdown } from '@/components/chat/markdown';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

export default async function SharedChatPage({
  params,
}: {
  params: { token: string };
}) {
  const { token } = await params;
  const chat = await getChatByToken(token);

  if (!chat) {
    notFound();
  }

  return (
    <div className="flex flex-col h-screen bg-background selection:bg-primary/20">
      {/* Premium Header */}
      <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-border/50 bg-background/60 px-6 backdrop-blur-xl transition-all duration-300">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary shadow-inner">
            <Heart className="h-6 w-6 stroke-[2.5px]" />
          </div>
          <div>
            <h1 className="text-base font-bold tracking-tight text-foreground">
              CardioAI Assessment
            </h1>
            <p className="text-[10px] font-medium uppercase tracking-widest text-muted-foreground/60">
              Shared Consultation
            </p>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <Link href="/login">
            <Button
              variant="outline"
              size="sm"
              className="hidden sm:flex rounded-full px-5 border-border/50 hover:bg-accent hover:text-foreground transition-all duration-300"
            >
              Get Started
            </Button>
          </Link>
          <Link href="/signup">
            <Button
              size="sm"
              className="rounded-full px-5 shadow-lg shadow-primary/20 transition-all duration-300 hover:shadow-primary/30 active:scale-95"
            >
              Sign Up
            </Button>
          </Link>
        </div>
      </header>

      <main className="flex-1 overflow-hidden relative">
        <ScrollArea className="h-full">
          <div className="max-w-3xl mx-auto py-12 px-6 space-y-12 pb-32">
            <div className="space-y-4 text-center pb-8 border-b border-border/10">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/5 border border-primary/10 text-[11px] font-bold text-primary uppercase tracking-wider animate-in fade-in zoom-in duration-500">
                <Share2 className="h-3 w-3" />
                Shared Results
              </div>
              <h2 className="text-3xl font-extrabold tracking-tight text-foreground sm:text-4xl">
                {chat.title || 'Heart Disease Risk Analysis'}
              </h2>
              <p className="text-muted-foreground text-sm max-w-md mx-auto">
                This assessment was generated by CardioAI based on a
                personalized conversation with the user.
              </p>
            </div>

            <div className="space-y-10">
              {chat.messages.map((msg, i) => (
                <div
                  key={msg.id}
                  className={`flex gap-6 group animate-in slide-in-from-bottom-4 duration-700 fade-in fill-mode-both ${msg.actor === 'USER' ? 'flex-row-reverse' : ''}`}
                  style={{ animationDelay: `${i * 100}ms` }}
                >
                  <Avatar
                    className={`h-10 w-10 shrink-0 shadow-lg ring-2 ring-background transition-transform duration-300 group-hover:scale-110 ${msg.actor === 'ASSISTANT' ? 'bg-primary text-primary-foreground shadow-primary/20' : 'bg-secondary ring-border/50'}`}
                  >
                    <AvatarFallback>
                      {msg.actor === 'ASSISTANT' ? (
                        <Bot className="h-5 w-5" />
                      ) : (
                        <UserIcon className="h-5 w-5" />
                      )}
                    </AvatarFallback>
                  </Avatar>
                  <div
                    className={`flex-1 space-y-2.5 ${msg.actor === 'USER' ? 'flex flex-col items-end' : ''}`}
                  >
                    <div
                      className={`flex items-center gap-2 ${msg.actor === 'USER' ? 'flex-row-reverse' : ''}`}
                    >
                      <p className="text-[13px] font-bold tracking-tight text-foreground/90 uppercase">
                        {msg.actor === 'ASSISTANT' ? 'Assistant' : 'User'}
                      </p>
                      <span className="h-1 w-1 rounded-full bg-border" />
                      <time className="text-[11px] text-muted-foreground/60 font-medium">
                        {new Date(msg.createdAt).toLocaleTimeString([], {
                          hour: '2-digit',
                          minute: '2-digit',
                        })}
                      </time>
                    </div>
                    <div
                      className={`text-[15px] leading-relaxed transition-all duration-300 ${
                        msg.actor === 'USER'
                          ? 'bg-primary/5 p-4 rounded-2xl rounded-tr-none text-foreground border border-primary/10'
                          : 'text-muted-foreground'
                      } prose prose-neutral dark:prose-invert max-w-none`}
                    >
                      <Markdown content={msg.message} />
                    </div>
                  </div>
                </div>
              ))}
            </div>

            <div className="pt-20 text-center animate-in fade-in slide-in-from-bottom-6 duration-1000 delay-500 fill-mode-both">
              <div className="p-8 rounded-3xl bg-gradient-to-b from-muted/30 to-background border border-border/50 shadow-sm">
                <Heart className="h-10 w-10 text-primary mx-auto mb-4 animate-pulse" />
                <h3 className="text-xl font-bold mb-2">
                  Want your own assessment?
                </h3>
                <p className="text-muted-foreground text-sm mb-6 max-w-xs mx-auto">
                  Start a private conversation with CardioAI to understand your
                  heart health risks today.
                </p>
                <Link href="/signup">
                  <Button className="rounded-full px-8 h-11 font-semibold shadow-xl shadow-primary/25">
                    Start Free Consultation
                  </Button>
                </Link>
              </div>
            </div>
          </div>
        </ScrollArea>
      </main>

      <footer className="py-6 px-6 border-t border-border/50 text-center bg-muted/20 backdrop-blur-md">
        <p className="text-[11px] font-medium text-muted-foreground/50 uppercase tracking-[0.2em]">
          Powered by CardioAI &copy; {new Date().getFullYear()} &bull; Medical
          Disclaimer
        </p>
      </footer>
    </div>
  );
}
